services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    
    environment:
      - TZ=America/Bogota
      - GENERIC_TIMEZONE=America/Bogota
      - N8N_HOST=tu-dominio.easypanel.host
      - N8N_WEBHOOK_URL=https://tu-dominio.easypanel.host
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_PROXY_HOPS=1
      - N8N_SECURE_COOKIE=false
      - NODE_FUNCTION_ALLOW_BUILTIN=stream
      - NODE_FUNCTION_ALLOW_EXTERNAL=mammoth,xlsx
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=Isaac2014
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
